# Generated by Django 4.2.16 on 2026-04-24 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licitaciones', '0006_rename_licitacion_estado_provincia_idx_licitacione_estado_a42196_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accio', models.CharField(choices=[('DESCARREGA', 'Descàrrega'), ('VISUALITZA', 'Visualització'), ('EDICIO', 'Edició'), ('ELIMINACIO', 'Eliminació')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Accés document',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('codi', models.CharField(max_length=20, unique=True)),
                ('descripcio', models.TextField(blank=True)),
                ('retencio_anys', models.PositiveIntegerField(default=5, help_text='Anys de retenció obligatoria (ISO 9001/14001)')),
                ('requereix_aprovacio', models.BooleanField(default=False)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoria document',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=300, verbose_name='Nom document')),
                ('descripcio', models.TextField(blank=True)),
                ('tipus', models.CharField(choices=[('PDF', 'PDF'), ('WORD', 'Word'), ('EXCEL', 'Excel'), ('IMATGE', 'Imatge'), ('VIDEO', 'Vídeo'), ('ALTRES', 'Altres')], default='ALTRES', max_length=20)),
                ('estat', models.CharField(choices=[('PUJANT', 'Pujant'), ('ACTIU', 'Actiu'), ('ARXIVAT', 'Arxivat'), ('ELIMINAT', 'Eliminat')], db_index=True, default='PUJANT', max_length=20)),
                ('s3_key', models.CharField(max_length=500, unique=True)),
                ('nom_fitxer_original', models.CharField(max_length=300)),
                ('mida_bytes', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('s3_version_id', models.CharField(blank=True, max_length=200)),
                ('metadades', models.JSONField(default=dict)),
                ('etiquetes', models.JSONField(default=list)),
                ('data_document', models.DateField(blank=True, null=True)),
                ('data_caducitat', models.DateField(blank=True, db_index=True, null=True)),
                ('data_eliminacio_prevista', models.DateField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualitzada_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.categoriadocument')),
                ('licitacio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='licitaciones.licitacion')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='VersioDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_versio', models.PositiveIntegerField()),
                ('s3_key', models.CharField(max_length=500)),
                ('s3_version_id', models.CharField(blank=True, max_length=200)),
                ('sha256', models.CharField(max_length=64)),
                ('mida_bytes', models.BigIntegerField(default=0)),
                ('notes_versio', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('creada_per', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
            ],
            options={
                'ordering': ['-numero_versio'],
            },
        ),
        migrations.CreateModel(
            name='PermisDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(blank=True, help_text='Rol de rrhh.UserProfile (ADMIN/JEFE/SUPERVISOR/TRABAJADOR)', max_length=20)),
                ('nivell', models.CharField(choices=[('LECTURA', 'Lectura'), ('EDICIO', 'Edició'), ('ADMIN', 'Administrador')], default='LECTURA', max_length=20)),
                ('atorgat_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField(blank=True, null=True)),
                ('atorgat_per', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='documents.document')),
                ('usuari', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permisos_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permís document',
            },
        ),
    ]
