# Generated by Django 4.2.16 on 2026-04-24 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ofertes', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='oferta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='ofertes.oferta'),
        ),
        migrations.AddField(
            model_name='document',
            name='propietari',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_propietari', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='pujat_per',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents_pujats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='versio_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.versiodocument'),
        ),
        migrations.AddField(
            model_name='categoriadocument',
            name='pare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fills', to='documents.categoriadocument'),
        ),
        migrations.AddField(
            model_name='accesdocument',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessos', to='documents.document'),
        ),
        migrations.AddField(
            model_name='accesdocument',
            name='usuari',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesdocument',
            name='versio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.versiodocument'),
        ),
        migrations.AlterUniqueTogether(
            name='versiodocument',
            unique_together={('document', 'numero_versio')},
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['categoria', 'estat'], name='documents_d_categor_46e49d_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['data_caducitat'], name='documents_d_data_ca_57075d_idx'),
        ),
    ]
