# Generated by Django 4.2.16 on 2026-04-24 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_initial'),
        ('licitaciones', '0006_rename_licitacion_estado_provincia_idx_licitacione_estado_a42196_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaRAG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('filtres', models.JSONField(default=dict)),
                ('context_recuperat', models.JSONField(default=list)),
                ('resposta', models.TextField(blank=True)),
                ('fonts_citades', models.JSONField(default=list)),
                ('model_usat', models.CharField(blank=True, max_length=100)),
                ('temps_ms', models.IntegerField(default=0)),
                ('estat', models.CharField(choices=[('EN_CURS', 'En curs'), ('COMPLETADA', 'Completada'), ('ERROR', 'Error')], default='EN_CURS', max_length=20)),
                ('error_msg', models.TextField(blank=True)),
                ('valoracio', models.IntegerField(blank=True, help_text='1-5', null=True)),
                ('comentari_valoracio', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('usuari', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta RAG',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='DocumentEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('font_tipus', models.CharField(choices=[('LICITACIO', 'Licitació (PDF plec)'), ('EXTRACCION', 'Extracció IA'), ('DOCUMENT', 'Document intern'), ('INFORME', 'Informe intern')], db_index=True, max_length=20)),
                ('font_id', models.CharField(db_index=True, max_length=100)),
                ('numero_chunk', models.PositiveIntegerField(default=0)),
                ('text_chunk', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('model_embedding', models.CharField(default='nomic-embed-text', max_length=100)),
                ('embedding_dim', models.PositiveIntegerField(default=768)),
                ('embedding', models.JSONField(default=list)),
                ('sha256_chunk', models.CharField(db_index=True, max_length=64)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='documents.document')),
                ('licitacio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='licitaciones.licitacion')),
            ],
            options={
                'verbose_name': 'Embedding document',
                'indexes': [models.Index(fields=['font_tipus', 'font_id'], name='rag_documen_font_ti_6ce142_idx'), models.Index(fields=['sha256_chunk'], name='rag_documen_sha256__fa898f_idx')],
                'unique_together': {('font_tipus', 'font_id', 'numero_chunk')},
            },
        ),
    ]
