# Generated by Django 4.2.16 on 2026-04-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertaconfig',
            name='procediments',
            field=models.JSONField(default=list, help_text='Llista de procediments. Buit = tots.'),
        ),
        migrations.AlterField(
            model_name='alertaconfig',
            name='provincies',
            field=models.JSONField(default=list, help_text='Llista de províncies. Buit = totes.'),
        ),
    ]
