# Generated by Django 4.2.16 on 2026-04-17 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_action_2a1328_idx',
            old_name='audit_action_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_model_n_20c0d3_idx',
            old_name='audit_model_obj_idx',
        ),
    ]
