# Generated by Django 4.2.16 on 2026-04-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0005_municipis_favorites'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='licitacion',
            new_name='licitacione_estado_a42196_idx',
            old_name='licitacion_estado_provincia_idx',
        ),
        migrations.RenameIndex(
            model_name='licitacion',
            new_name='licitacione_fecha_p_fba4b4_idx',
            old_name='licitacion_fecha_pub_idx',
        ),
        migrations.RenameIndex(
            model_name='licitacion',
            new_name='licitacione_importe_1e2da9_idx',
            old_name='licitacion_importe_idx',
        ),
        migrations.AlterField(
            model_name='contacteprovincial',
            name='rol',
            field=models.CharField(choices=[('SUBCONTRACTISTA', 'Subcontratista'), ('PROVEIDOR', 'Proveedor'), ('DELEGAT', 'Delegado local'), ('TECNIC', 'Técnico / Arquitecto'), ('ALTRE', 'Otro')], default='ALTRE', max_length=20),
        ),
        migrations.AlterField(
            model_name='informeintern',
            name='recomendacio',
            field=models.CharField(choices=[('PRESENTAR', 'Presentar oferta'), ('DESCARTAR', 'Descartar'), ('ESTUDIAR', 'Estudiar más')], default='ESTUDIAR', max_length=20),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='estado',
            field=models.CharField(choices=[('NUEVA', 'Nueva'), ('REVISADA', 'Revisada'), ('DESCARTADA', 'Descartada'), ('EN_PREPARACION', 'En preparación'), ('PRESENTADA', 'Presentada'), ('ADJUDICADA', 'Adjudicada'), ('DESIERTA', 'Desierta')], db_index=True, default='NUEVA', max_length=20),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='procedimiento',
            field=models.CharField(choices=[('ABIERTO', 'Abierto'), ('RESTRINGIDO', 'Restringido'), ('NEGOCIADO', 'Negociado'), ('SIMPLIFICADO', 'Simplificado'), ('OTRO', 'Otro')], default='ABIERTO', max_length=20),
        ),
    ]
