# Generated by Django 4.2.16 on 2026-04-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_singleton_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapingtemplate',
            options={'verbose_name': 'Plantilla de scraping', 'verbose_name_plural': 'Plantilles de scraping'},
        ),
        migrations.RemoveConstraint(
            model_name='scrapingtemplate',
            name='only_one_template',
        ),
        migrations.AlterField(
            model_name='scrapingtemplate',
            name='nom',
            field=models.CharField(default='Default', max_length=200),
        ),
    ]
