# Generated by Django 4.2.16 on 2026-04-17 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_add_municipis'),
        ('scraping', '0004_alter_scrapingtemplate_options_and_more'),
    ]

    operations = [
    ]
