# Generated by Django 4.2.16 on 2026-04-24 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licitaciones', '0006_rename_licitacion_estado_provincia_idx_licitacione_estado_a42196_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estat', models.CharField(choices=[('BORRADOR', 'Esborrany'), ('EN_REVISIO', 'En revisió'), ('APROVADA', 'Aprovada'), ('ENVIADA', 'Enviada'), ('GUANYADA', 'Guanyada'), ('PERDUDA', 'Perduda'), ('RETIRADA', 'Retirada')], db_index=True, default='BORRADOR', max_length=20, verbose_name='Estat')),
                ('preu_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Preu oferta (€)')),
                ('preu_optim_calculat', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Preu òptim calculat (€)')),
                ('puntuacio_economica', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Puntuació econòmica estimada')),
                ('puntuacio_tecnica', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Puntuació tècnica estimada')),
                ('puntuacio_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Puntuació total estimada')),
                ('nivell_risc', models.CharField(choices=[('BAIX', 'Baix'), ('MITJA', 'Mitjà'), ('ALT', 'Alt')], default='MITJA', max_length=10, verbose_name='Nivell de risc')),
                ('factors_risc', models.JSONField(default=list, verbose_name='Factors de risc')),
                ('fortaleses', models.JSONField(default=list, verbose_name='Fortaleses')),
                ('debilitats', models.JSONField(default=list, verbose_name='Debilitats')),
                ('notes_internes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('justificacio_preu', models.TextField(blank=True, verbose_name='Justificació del preu')),
                ('pdf_oferta_s3_key', models.CharField(blank=True, max_length=500, verbose_name='PDF oferta S3')),
                ('pdf_tecnica_s3_key', models.CharField(blank=True, max_length=500, verbose_name='PDF tècnica S3')),
                ('pdf_seguretat_s3_key', models.CharField(blank=True, max_length=500, verbose_name='PDF pla seguretat S3')),
                ('data_presentacio', models.DateTimeField(blank=True, null=True, verbose_name='Data presentació')),
                ('data_resolucio', models.DateTimeField(blank=True, null=True, verbose_name='Data resolució')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualitzada_en', models.DateTimeField(auto_now=True)),
                ('licitacio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oferta', to='licitaciones.licitacion', verbose_name='Licitació')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofertes_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofertes_revisor', to=settings.AUTH_USER_MODEL, verbose_name='Revisor')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertes',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudSubcontractista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partides', models.JSONField(default=list, verbose_name='Partides sol·licitades')),
                ('estat', models.CharField(choices=[('PENDENT', 'Pendent'), ('ENVIADA', 'Enviada'), ('REBUDA', 'Rebuda'), ('ACCEPTADA', 'Acceptada'), ('REBUTJADA', 'Rebutjada')], default='PENDENT', max_length=20)),
                ('preu_resposta', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes_resposta', models.TextField(blank=True)),
                ('token_resposta', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('resposta_en', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('contacte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitaciones.contacteprovincial')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicituds_subcontractista', to='ofertes.oferta')),
            ],
            options={
                'verbose_name': 'Sol·licitud subcontractista',
            },
        ),
        migrations.CreateModel(
            name='Pressupost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(max_length=200, verbose_name='Títol')),
                ('versio', models.PositiveIntegerField(default=1)),
                ('actiu', models.BooleanField(db_index=True, default=True)),
                ('cost_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualitzada_en', models.DateTimeField(auto_now=True)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pressupostos', to='ofertes.oferta')),
            ],
            options={
                'verbose_name': 'Pressupost',
                'verbose_name_plural': 'Pressupostos',
                'ordering': ['-versio'],
            },
        ),
        migrations.CreateModel(
            name='PlaSeguretat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partides_obra', models.JSONField(default=list, verbose_name='Partides obra')),
                ('contingut_ia', models.TextField(blank=True, verbose_name='Contingut generat per IA')),
                ('contingut_revisat', models.TextField(blank=True, verbose_name='Contingut revisat')),
                ('prompt_versio', models.CharField(default='v1', max_length=20)),
                ('model_usat', models.CharField(blank=True, max_length=100)),
                ('validat', models.BooleanField(default=False)),
                ('validat_en', models.DateTimeField(blank=True, null=True)),
                ('pdf_s3_key', models.CharField(blank=True, max_length=500)),
                ('generat_en', models.DateTimeField(auto_now_add=True)),
                ('actualitzat_en', models.DateTimeField(auto_now=True)),
                ('oferta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pla_seguretat', to='ofertes.oferta')),
                ('validat_per', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pla de Seguretat i Salut',
            },
        ),
        migrations.CreateModel(
            name='LiniaPressupost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipus', models.CharField(choices=[('MA_DOBRA', "Mà d'obra"), ('MATERIALS', 'Materials'), ('SUBCONTRACTA', 'Subcontracta'), ('EQUIPAMENT', 'Equipament'), ('INDIRECT', 'Costos indirectes'), ('ALTRES', 'Altres')], max_length=20)),
                ('descripcio', models.CharField(max_length=500)),
                ('unitat', models.CharField(blank=True, max_length=50)),
                ('quantitat', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('cost_unitari', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('pressupost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linies', to='ofertes.pressupost')),
                ('subcontractista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linies_pressupost', to='licitaciones.contacteprovincial')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VersioOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_versio', models.PositiveIntegerField()),
                ('snap_data', models.JSONField()),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('creada_per', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ofertes.oferta')),
            ],
            options={
                'ordering': ['-numero_versio'],
                'unique_together': {('oferta', 'numero_versio')},
            },
        ),
    ]
