# Generated by Django 4.2.16 on 2026-04-24 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licitaciones', '0006_rename_licitacion_estado_provincia_idx_licitacione_estado_a42196_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendariConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_access_token', models.TextField(blank=True)),
                ('ms_refresh_token', models.TextField(blank=True)),
                ('ms_token_expiry', models.DateTimeField(blank=True, null=True)),
                ('ms_calendar_id', models.CharField(blank=True, max_length=200)),
                ('sincronitzar_licitacions', models.BooleanField(default=True)),
                ('sincronitzar_ofertes', models.BooleanField(default=True)),
                ('dies_avis_previ', models.PositiveIntegerField(default=3)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualitzada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuració calendari',
            },
        ),
        migrations.CreateModel(
            name='Esdeveniment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipus', models.CharField(choices=[('TERMINI_LICITACIO', 'Termini licitació'), ('REUNIO_INTERNA', 'Reunió interna'), ('PRESENTACIO_OFERTA', 'Presentació oferta'), ('APERTURA_PLIQUES', 'Obertura de pliques'), ('SEGUIMENT', 'Seguiment'), ('ALTRES', 'Altres')], max_length=30)),
                ('titol', models.CharField(max_length=300)),
                ('descripcio', models.TextField(blank=True)),
                ('ubicacio', models.CharField(blank=True, max_length=300)),
                ('inici', models.DateTimeField(db_index=True)),
                ('fi', models.DateTimeField()),
                ('tot_el_dia', models.BooleanField(default=False)),
                ('recordatori_minuts', models.PositiveIntegerField(default=60)),
                ('estat', models.CharField(choices=[('PENDENT', 'Pendent'), ('SINCRONIT', 'Sincronitzat'), ('ERROR', 'Error sincronització'), ('CANCEL_LAT', 'Cancel·lat')], default='PENDENT', max_length=20)),
                ('ms_event_id', models.CharField(blank=True, max_length=500)),
                ('error_msg', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualitzada_en', models.DateTimeField(auto_now=True)),
                ('assistents', models.ManyToManyField(blank=True, related_name='esdeveniments_assignats', to=settings.AUTH_USER_MODEL)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esdeveniments_creats', to=settings.AUTH_USER_MODEL)),
                ('licitacio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esdeveniments', to='licitaciones.licitacion')),
            ],
            options={
                'verbose_name': 'Esdeveniment',
                'verbose_name_plural': 'Esdeveniments',
                'ordering': ['inici'],
            },
        ),
    ]
