# Generated by Django 4.2.16 on 2026-04-24 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ofertes', '0001_initial'),
        ('calendari', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='esdeveniment',
            name='oferta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esdeveniments', to='ofertes.oferta'),
        ),
        migrations.AddField(
            model_name='calendariconfig',
            name='usuari',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendari_config', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='esdeveniment',
            index=models.Index(fields=['inici', 'fi'], name='calendari_e_inici_e0865b_idx'),
        ),
        migrations.AddIndex(
            model_name='esdeveniment',
            index=models.Index(fields=['estat'], name='calendari_e_estat_e39281_idx'),
        ),
    ]
