# Generated by Django 4.2.16 on 2026-04-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaje',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fichaje',
            name='tipus',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('TELETREBALL', 'Teletrabajo'), ('GUARDIA', 'Guardia')], default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('JEFE', 'Jefe'), ('SUPERVISOR', 'Supervisor'), ('TRABAJADOR', 'Trabajador')], db_index=True, default='TRABAJADOR', max_length=20),
        ),
    ]
