# Generated by Django 4.2.16 on 2026-04-24 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licitaciones', '0006_rename_licitacion_estado_provincia_idx_licitacione_estado_a42196_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaProspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('sector', models.CharField(choices=[('CONSTRUCCIO', 'Construcció'), ('ENGINYERIA', 'Enginyeria'), ('PROMOTORA', 'Promotora'), ('ADMINISTRACIO', 'Administració pública'), ('AUTRES', 'Altres')], default='CONSTRUCCIO', max_length=30)),
                ('origen', models.CharField(choices=[('MANUAL', 'Manual'), ('LICITACIO', 'Licitació (organisme)'), ('IMPORTACIO', 'Importació'), ('REFERENCIA', 'Referència')], default='MANUAL', max_length=20)),
                ('estat', models.CharField(choices=[('PROSPECCIO', 'Prospecció'), ('CONTACTAT', 'Contactat'), ('INTERESSAT', 'Interessat'), ('CLIENT', 'Client'), ('DESCARTAT', 'Descartat')], db_index=True, default='PROSPECCIO', max_length=20)),
                ('email_principal', models.EmailField(blank=True, max_length=254)),
                ('emails_alternatius', models.JSONField(default=list)),
                ('telefon', models.CharField(blank=True, max_length=30)),
                ('web', models.URLField(blank=True)),
                ('direccio', models.CharField(blank=True, max_length=300)),
                ('poblacio', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=50)),
                ('persona_contacte', models.CharField(blank=True, max_length=200)),
                ('carrec_contacte', models.CharField(blank=True, max_length=100)),
                ('scoring', models.FloatField(db_index=True, default=0.0)),
                ('notes', models.TextField(blank=True)),
                ('consentiment_gdpr', models.BooleanField(default=False)),
                ('data_consentiment', models.DateTimeField(blank=True, null=True)),
                ('baixa_voluntaria', models.BooleanField(default=False)),
                ('data_baixa', models.DateTimeField(blank=True, null=True)),
                ('token_baixa', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualitzada_en', models.DateTimeField(auto_now=True)),
                ('assignat_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('licitacio_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licitaciones.licitacion')),
            ],
            options={
                'verbose_name': 'Empresa prospecte',
                'verbose_name_plural': 'Empreses prospecte',
                'ordering': ['-scoring', '-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('tipus', models.CharField(choices=[('PROSPECCIO', 'Prospecció inicial'), ('SEGUIMENT', 'Seguiment'), ('PRESENTACIO', 'Presentació empresa'), ('OFERTA_SERVEI', 'Oferta de servei')], max_length=30)),
                ('idioma', models.CharField(default='ca', max_length=5)),
                ('assumpte', models.CharField(max_length=300)),
                ('cos_text', models.TextField()),
                ('cos_html', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualitzada_en', models.DateTimeField(auto_now=True)),
                ('creada_per', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla email',
            },
        ),
        migrations.CreateModel(
            name='CampanyaMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('estat', models.CharField(choices=[('ESBORRANY', 'Esborrany'), ('PROGRAMADA', 'Programada'), ('EN_CURS', 'En curs'), ('COMPLETADA', 'Completada'), ('PAUSADA', 'Pausada')], default='ESBORRANY', max_length=20)),
                ('segments', models.JSONField(default=dict, help_text='Filtres: {"sector": ["CONSTRUCCIO"], "provincia": ["Valencia"], "scoring_min": 5.0}')),
                ('millorar_amb_ia', models.BooleanField(default=True)),
                ('personalitzar_per_empresa', models.BooleanField(default=True)),
                ('data_programada', models.DateTimeField(blank=True, null=True)),
                ('total_destinataris', models.IntegerField(default=0)),
                ('total_enviats', models.IntegerField(default=0)),
                ('total_errors', models.IntegerField(default=0)),
                ('total_obertures', models.IntegerField(default=0)),
                ('total_clics', models.IntegerField(default=0)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('iniciada_en', models.DateTimeField(blank=True, null=True)),
                ('completada_en', models.DateTimeField(blank=True, null=True)),
                ('creada_per', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketing.plantillaemail')),
            ],
            options={
                'verbose_name': 'Campanya marketing',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='EnviamentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assumpte_final', models.CharField(max_length=300)),
                ('cos_final_text', models.TextField()),
                ('cos_final_html', models.TextField(blank=True)),
                ('estat', models.CharField(choices=[('PENDENT', 'Pendent'), ('ENVIANT', 'Enviant'), ('ENVIAT', 'Enviat'), ('ERROR', 'Error'), ('REBUTJAT', 'Rebutjat (bounce)')], db_index=True, default='PENDENT', max_length=20)),
                ('error_msg', models.TextField(blank=True)),
                ('tracking_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('obert', models.BooleanField(default=False)),
                ('obert_en', models.DateTimeField(blank=True, null=True)),
                ('clicat', models.BooleanField(default=False)),
                ('clicat_en', models.DateTimeField(blank=True, null=True)),
                ('enviat_en', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('campanya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enviaments', to='marketing.campanyamarketing')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enviaments', to='marketing.empresaprospect')),
            ],
            options={
                'verbose_name': 'Enviament email',
                'indexes': [models.Index(fields=['estat', 'creada_en'], name='marketing_e_estat_349a0b_idx')],
                'unique_together': {('campanya', 'prospect')},
            },
        ),
        migrations.AddIndex(
            model_name='empresaprospect',
            index=models.Index(fields=['sector', 'estat'], name='marketing_e_sector_a73eb7_idx'),
        ),
        migrations.AddIndex(
            model_name='empresaprospect',
            index=models.Index(fields=['baixa_voluntaria'], name='marketing_e_baixa_v_4adecc_idx'),
        ),
    ]
